# Generated by Django 5.2.7 on 2025-11-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='num_people',
            new_name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default='2025-01-02'),
        ),
        migrations.AddField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default='2025-01-01'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
